services:
  webapi:
    build:
      context: ./Project.Api/Project.Api
      dockerfile: Dockerfile
    hostname: webapi
    container_name: webapi
    ports:
      - "7132:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - Project-network

  reactapp:
    build:
      context: ./Project.Web
      dockerfile: Dockerfile
    hostname: reactapp
    ports:
      - "5173:5173"
    networks:
      - Project-network
    environment:
      VITE_API_URL: http://localhost:7132/api

networks:
  Project-network:
    driver: bridge
